version: '3'

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - 443:443
    depends_on: 
      - wordpress
    volumes:
      - /data/html:/var/www/html
    networks:
      - wordpress
  wordpress:
    build: ./requirements/wordpress
    volumes:
      - /data/html:/var/www/html
    networks:
      - wordpress
#  mariadb:
#    build: ./requirements/mariadb
#    ports:
#      - 3306:3306

networks: 
  wordpress:
    driver: bridge