version: '3'

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - .tools/data/html:/var/www/html/wordpress
  wordpress:
    build: ./requirements/wordpress
    volumes: 
      - ./tools/data/html:/var/www/html/wordpress
#  mariadb:
#    build: ./requirements/mariadb
#    ports:
#      - 3306:3306

